# Project
version=21.1
group=net.darkhax.botanypots
java_version=21

# Mod
mod_name=BotanyPots
mod_author=Darkhax
mod_id=botanypots
mod_license=LGPL v2.1
mod_description=Pots for growing different types of plants.
mod_repo=https://github.com/Darkhax-Minecraft/BotanyPots
mod_docs=https://docs.darkhax.net/mods/botany-pots
mod_item_icon=minecraft:brick

# Build Flags
mod_client_only=false

# Common
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_form_version=1.21.1-20240808.144430
parchment_minecraft=1.21
parchment_version=2024.07.28
bookshelf_version=21.1.56
bookshelf_version_range=[21.1.56, 21.2)
prickle_version=21.1.4
prickle_version_range=[21.1, 21.2)
simple_loot_viewer_version=21.1.2
jei_version=19.18.10.218
crt_version=21.0.3

# NeoForge
neoforge_version=21.1.61
neoforge_loader_version_range=[4,)

# Fabric
fabric_version=0.105.0+1.21.1
fabric_loader_version=0.16.4
modmenu_version=11.0.2

# Forge
forge_version=52.0.16
forge_loader_version_range=[52,)
forge_version_range=[52.0.16,)

# CurseForge
curse_project=353928
curse_page=https://www.curseforge.com/minecraft/mc-mods/botany-pots

# Modrinth
modrinth_project=U6BUTZ7K
modrinth_page=https://modrinth.com/mod/botany-pots

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false